#!/usr/bin/python3
"""
<Program Name>
  http

<Author>
  Lukas Puehringer <lukas.puehringer@nyu.edu>

<Started>
  December 06, 2018.

<Copyright>
  See LICENSE for licensing information.

<Purpose>
  Mock apt built-in http transport for testing. This has to be an executable
  in the same directory as the intoto transport. It is implemented in
  tests/test_intoto.py.

"""
import tests.test_intoto
tests.test_intoto.mock_http()
